title: "Vokyo"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
aux_links:
    "See you at DexCon":
      - "//dexposure.com"
footer_content: "Copyright &copy; 2019 Omega Direx"

